-- BORRAR TABLAS 

DROP TABLE EPS CASCADE CONSTRAINT;
DROP TABLE ESTABLECIMIENTOS CASCADE CONSTRAINT;
DROP TABLE CURSOS CASCADE CONSTRAINT;
DROP TABLE EMPLEADOS CASCADE CONSTRAINT;
DROP TABLE CURSOS_VIGILANTES CASCADE CONSTRAINT;
DROP TABLE CONTRATOS CASCADE CONSTRAINT;