-- CREACION DE LAS RESTRICCIONES DE LA TABLA CONTRATOS

ALTER TABLE CONTRATOS ADD(
    CONSTRAINT CON_FK_IDE FOREIGN KEY (ID_EMP) REFERENCES EMPLEADOS(ID_EMP),
    CONSTRAINT CON_FK_IDES FOREIGN KEY (ID_EST) REFERENCES ESTABLECIMIENTOS(ID_EST),
    CONSTRAINT CON_CK_TCO CHECK(TIPO_CONTRATO in ('P'/*PRSTACION SERVICIOS*/, 'L'/*LABORAL*/)),
    CONSTRAINT CON_CK_TCL CHECK(TIPO_CONTRATO_LABORAL in ('F'/*TERMINO FIJO*/, 'I'/*TERMINO INDEFINIDO*/)),
    CONSTRAINT CON_CK_THO CHECK(TIPO_HORARIO in ('1'/*8H DIURNO*/, '2'/*8H NOCTURNO*/,'3'/*12H DIURNO*/, '4'/*12H NOCTURNO*/))
);