-- CREACION DE LAS RESTRICCIONES DE LA TABLA ESTABLECIMIENTOS

ALTER TABLE ESTABLECIMIENTOS ADD(
    CONSTRAINT EST_UQ_NOM UNIQUE(NOMBRE_EST),
    CONSTRAINT EST_CK_TES CHECK(TIPO_EST in ('U'/*URBANIZACION*/, 'C'/*COMERCIAL*/, 'A'/*ABIERTO*/,'O'/*OTROS*/))
);