-- CRETE TABLE CURSOS

CREATE TABLE CURSOS(
    ID_CURSO            NUMBER(11)      NOT NULL,
    ESPECIALIDAD_CURSO  VARCHAR2(30)    NOT NULL,
    CONSTRAINT  CUS_PK_IDC  PRIMARY KEY (ID_CURSO)
);
